# Generated by Django 4.2.4 on 2024-03-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='author',
        ),
    ]
