# Generated by Django 4.2.4 on 2024-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_model',
            name='short_content',
            field=models.TextField(max_length=500),
        ),
    ]
