# Generated by Django 4.2.4 on 2024-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_model_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
