# Generated by Django 4.2.4 on 2024-03-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_model_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post_model',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post_model',
            name='post_tags',
            field=models.ManyToManyField(to='blog.post_tag'),
        ),
    ]
