# Generated by Django 4.2.4 on 2024-03-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tag_alter_post_model_slug_post_model_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post_tag',
            name='tag_url',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='short_content',
            field=models.CharField(db_index=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='tag',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
