# Generated by Django 4.2.4 on 2024-03-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_model_is_delete_post_tag_tag_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='is_delete',
        ),
        migrations.AlterField(
            model_name='post_model',
            name='content',
            field=models.TextField(),
        ),
    ]
