# Generated by Django 4.2.4 on 2024-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_model_is_delete_alter_post_model_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tag',
            name='tag',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post_tag',
            name='tag_url',
            field=models.SlugField(blank=True, default='', max_length=150, unique=True),
        ),
    ]
