# Generated by Django 4.2.4 on 2024-03-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_tag_tag_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_tag',
            name='tag_url',
        ),
    ]
