# Generated by Django 4.2.4 on 2024-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_tag_tag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
