# Generated by Django 4.2.4 on 2024-04-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_model_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='date',
        ),
    ]
